version: "1.0"
info:
  model: int-scaffold
packages:
- name: JGrouptestListenerProject
  gitServerName: amkuGit_1
  gitUrl: https://github.com/amkuamrk
  gitUsername: amkuamrk
  gitBranch: main
- name: WmSalesforceProvider
  version: 12.0.0.0.22
  wpmServer: https://packages.webmethods.io
  wpmRegistry: supported
services:
- serviceName: project.jgrouptestlistener.WmSalesforceProvider.com_webmethods_cloudstreams_salesforce_v53.connections:listenertestaccount
  packages:
  - name: JGrouptestListenerProject
    version: "1.0"
  - name: WmSalesforceProvider
    version: 12.0.0.0.22
