version: "1.0"
info:
  model: int-scaffold
packages:
- name: JGrouptestListenerProject
  gitServerName: amkuGit_1
  gitUrl: https://github.com/amkuamrk
  gitUsername: amkuamrk
  gitBranch: main
- name: WmSalesforceProvider
  version: 12.0.0.0.22
  wpmServer: https://packages.webmethods.io
  wpmRegistry: supported
- name: WmCloudStreams
  version: 12.1.0
  wpmServer: https://packages.webmethods.io
  wpmRegistry: licensed
services:
- serviceName: project.jgrouptestlistener.JGrouptestListenerProject.project_jgrouptestlistener_JGrouptestListenerProject_ramuKaka.connections:ramuconnec
  packages:
  - name: JGrouptestListenerProject
    version: "1.0"
  - name: WmCloudStreams
    version: 12.1.0.0.80
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmSalesforceProvider
    version: 12.0.0.0.23
- serviceName: project.jgrouptestlistener.WmSalesforceProvider.com_webmethods_cloudstreams_salesforce_v53.operations.actions:createAccount
  packages:
  - name: JGrouptestListenerProject
    version: "1.0"
  - name: WmCloudStreams
    version: 12.1.0.0.80
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmSalesforceProvider
    version: 12.0.0.0.23
- serviceName: project.jgrouptestlistener.WmSalesforceProvider.com_webmethods_cloudstreams_salesforce_v53.operations.actions:deleteAccount
  packages:
  - name: JGrouptestListenerProject
    version: "1.0"
  - name: WmCloudStreams
    version: 12.1.0.0.80
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmSalesforceProvider
    version: 12.0.0.0.23
- serviceName: project.jgrouptestlistener.WmSalesforceProvider.com_webmethods_cloudstreams_salesforce_v53.operations.actions:new_flowservice
  packages:
  - name: JGrouptestListenerProject
    version: "1.0"
  - name: WmCloudStreams
    version: 12.1.0.0.80
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmSalesforceProvider
    version: 12.0.0.0.23
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 12.1.0.0.1022
- serviceName: project.jgrouptestlistener.WmSalesforceProvider.com_webmethods_cloudstreams_salesforce_v53.operations.actions:tedt
  packages:
  - name: JGrouptestListenerProject
    version: "1.0"
  - name: WmCloudStreams
    version: 12.1.0.0.80
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmSalesforceProvider
    version: 12.0.0.0.23
- serviceName: project.jgrouptestlistener.WmSalesforceProvider.com_webmethods_cloudstreams_salesforce_v53.operations.actions:updateaa
  packages:
  - name: JGrouptestListenerProject
    version: "1.0"
  - name: WmCloudStreams
    version: 12.1.0.0.80
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmSalesforceProvider
    version: 12.0.0.0.23
- serviceName: project.jgrouptestlistener.integrations:lisTest
  packages:
  - name: JGrouptestListenerProject
    version: "1.0"
  - name: WmCloudStreams
    version: 12.1.0.0.80
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmSalesforceProvider
    version: 12.0.0.0.23
